WITH MODULESIZE AS(
    SELECT moduleID, COUNT(studentID) as numStudents
    FROM STUDENTMODULES
    GROUP BY moduleID
)

SELECT MODULESIZE.moduleID, BUILDINGS.building, ROOMS.room
FROM MODULESIZE
JOIN LECTURERMODULES ON MODULESIZE.moduleID = LECTURERMODULES.moduleID
JOIN LECTURERFACULTY ON LECTURERMODULES.lecturer_email = LECTURERFACULTY.lecturer_email
JOIN BUILDINGS ON LECTURERFACULTY.faculty = BUILDINGS.faculty
JOIN ROOMS ON BUILDINGS.building = ROOMS.building
WHERE MODULESIZE.numStudents > ROOMS.capacity
ORDER BY MODULESIZE.moduleID, BUILDINGS.building, ROOMS.room;