WITH ALLMARKS AS (
    SELECT moduleID, exam_mark AS mark
    FROM STUDENTMODULES
    WHERE exam_mark IS NOT NULL

    UNION ALL

    SELECT moduleID, mark AS mark
    FROM COURSEWORKMARKS
    WHERE mark IS NOT NULL
),
MODULEAVGS AS (
    SELECT MODULES.moduleID, MODULES.leader, LECTURERFACULTY.faculty, AVG(ALLMARKS.mark) AS moduleAVG
    FROM MODULES
    JOIN LECTURERFACULTY ON MODULES.leader = LECTURERFACULTY.lecturer_email
    JOIN ALLMARKS ON MODULES.moduleID = ALLMARKS.moduleID
    GROUP BY MODULES.moduleID, MODULES.leader, LECTURERFACULTY.faculty
)
SELECT *
FROM MODULEAVGS
WHERE moduleAVG = (
    SELECT MAX(moduleAVG)
    FROM MODULEAVGS
    WHERE faculty = MODULEAVGS.faculty
)