SELECT STUDENTMODULES.moduleID, BUILDINGS.building, ROOMS.room
FROM BUILDINGS
JOIN ROOMS ON BUILDINGS.building = ROOMS.building
JOIN LECTURERFACULTY ON BUILDINGS.faculty = LECTURERFACULTY.faculty
JOIN LECTURERMODULES ON LECTURERFACULTY.lecturer_email = LECTURERMODULES.lecturer_email
JOIN STUDENTMODULES ON LECTURERMODULES.moduleID = STUDENTMODULES.moduleID
WHERE COUNT(STUDENTMODULES.studentID) > ROOMS.capacity
GROUP BY STUDENTMODULES.moduleID